allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Dependency locking is STRICT in CI and LENIENT for local dev, selected by
// the `lockMode` Gradle property (CI sets ORG_GRADLE_PROJECT_lockMode=STRICT):
//   - STRICT: the committed app/gradle.lockfile (generated by an all-ABI build)
//     is fully enforced — CI's fat + --split-per-abi builds resolve every ABI
//     present in the lock state, so strict verification is correct there.
//   - LENIENT (default, local dev): `flutter run` targets a single ABI
//     (e.g. -Ptarget-platform=android-x64) and legitimately resolves only that
//     ABI's engine artifacts; a separate dev lockfile keeps those resolutions
//     out of the committed CI lockfile while pinning versions where possible.
val lockMode = (findProperty("lockMode") as String?) ?: "LENIENT"
val isStrictLocking = lockMode.equals("STRICT", ignoreCase = true)

dependencyLocking {
    lockAllConfigurations()
    lockMode = if (isStrictLocking) LockMode.STRICT else LockMode.LENIENT
    if (!isStrictLocking) {
        lockFile = layout.projectDirectory.file("gradle.dev.lockfile")
    }
}

subprojects {
    dependencyLocking {
        lockAllConfigurations()
        lockMode = if (isStrictLocking) LockMode.STRICT else LockMode.LENIENT
        if (!isStrictLocking) {
            lockFile = layout.projectDirectory.file("gradle.dev.lockfile")
        }
    }
}

val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
